29기 최형택 [ADD] housedetail
wecode-bootcamp-korea/29-2nd-Airhnb-backend pull request #3
Opened 2022-02-21 06:01 UTC by knuckles6974

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)

- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)

- 아이디, 비밀번호 입력창을 사용한 로그인 기능 구현 (예시)

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)

<br />

## :: 기타 질문 및 특이 사항

2022-02-22 08:15 UTC, lordmyshepherd requested changes

2022-02-22 08:15 UTC, lordmyshepherd commented on cities.csv
> +country_id,name
.csv 파일은 올라오지 않도록 .gitignore 파일에 추가해주시고 프로젝트 폴더 내에서 지우거나 옮겨주셔서 올라오지 않도록 해주세요~

2022-02-22 08:15 UTC, lordmyshepherd commented on countries.csv
> +name
마찬가지입니다.

2022-02-22 08:15 UTC, lordmyshepherd commented on houses/views.py
> +    #    return JsonResponse({'data': data}, status=200)
주석은 전부 지워주세요~

2022-02-22 08:15 UTC, lordmyshepherd commented on houses/views.py
> +        house = House.objects.get(id=house_id)
- 피드백 1. db에서 데이터 하나를 가져올때에는 filter 보다는 get을 사용해주세요. 
- 피드백 2. `houseimage = HouseImage.objects.filter(id=house_id)` 이 코드는 아래 아무곳에서도 사용되고 있지 않습니다. 지워주세요.

```suggestion
        houses = House.objects.get(id = house_id)
        house = House.objects.get(id=house_id)
```

2022-02-22 08:15 UTC, lordmyshepherd commented on houses/views.py
> +        }for house in houses]
- 피드백 3. 해당 View는 `HouseDetailView`로 House 정보 하나만 반환하는 View가 되어야 합니다. 그런데 결과(result)는 리스트로 반환하고 있습니다. 아래와 같이 house 객체 하나만 반환하도록 해주세요.

```suggestion
        result = 
        {
            'house_id': house.id,
            'name' : house.name,
            'description' : house.description,
            'latitude' : house.latitude,
            'longitude': house.longitude,
            'house_type': house.house_type.name,
            'max_guest' : house.max_guest,
            'country': house.city.country.name,
            'city' : house.city.name,
            'reservation': house.reservation_set.all(),
            'trap' : house.trap,
            'exit' : house.exit,
            'houseimage' : [
                    houseimage.image_url.split('/')[-1].split('.')[0]
                    for houseimage in house.houseimage_set.all()],
        }
```

2022-02-22 08:15 UTC, lordmyshepherd commented on houses/views.py
> +          return JsonResponse({'Message':'house_id ERROR'}, status=400)
이 코드는 목적이 무엇인가요?

2022-02-22 08:51 UTC, knuckles6974 commented on houses/views.py
> +          return JsonResponse({'Message':'house_id ERROR'}, status=400)
일어나지 않은 상황을 생각해서 고려한것같습니다.  필터링할때 생각을 좀 깊게 해보겠습니다.

2022-02-23 05:25 UTC, lordmyshepherd requested changes

2022-02-23 05:25 UTC, lordmyshepherd commented on houses.csv
> +name,description,latitude,longitude,max_guest,trap,exit,ghost_id,city_id,house_type_id,user_id
모든 .csv 파일 전부 올라오지 않도록 수정해주세요.

2022-02-23 05:25 UTC, lordmyshepherd commented on houses/urls.py
> +}
```suggestion
urlpatterns = [
    path('/<int:house_id>', HouseDetailView.as_view()),
]
```

2022-02-23 05:25 UTC, lordmyshepherd commented on houses/views.py
> +
```suggestion
```

2022-02-23 05:25 UTC, lordmyshepherd commented on houses/views.py
> +                        for houseimage in house.houseimage_set.all()],
```suggestion
                'houseimage' : [houseimage.image_url for houseimage in house.houseimage_set.all()],
```

2022-02-23 05:25 UTC, lordmyshepherd commented on houses/views.py
> +                'reservation': list(house.reservation_set.all().filter().values()),
```suggestion
                'reservation': list(house.reservation_set.all().values()),
```

2022-02-23 05:25 UTC, lordmyshepherd commented on reservations/views.py
> -from django.shortcuts import render
PR 분리해서 올려주세요~

2022-02-23 07:57 UTC, lordmyshepherd approved these changes
LGTM 👍🏻

2022-02-23 08:06 UTC, lordmyshepherd approved these changes
LGTM 👍🏻

2022-02-23 08:06 UTC, merged