Feature/being the host
wecode-bootcamp-korea/29-2nd-Airhnb-backend pull request #5
Opened 2022-02-21 06:39 UTC by jxngbxxm

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)

- [ ] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)

- 아이디, 비밀번호 입력창을 사용한 로그인 기능 구현 (예시)

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)

1. 로그인 입력 데이터 유효성 검사 (예시 - 프론트)

- 입력창에 변화가 일어날 때 마다 유효성 검사 함수가 실행된다.
- 유효성 검사 함수의 반환값(boolean)에 따라 버튼의 배경색과 disabled 속성이 변화한다.
- 테스트 방법 : `/login` 페이지 이동 >>> 로그인 input 데이터 입력

2. 로그인 데이터 처리 (예시 - 백엔드)

- 조건문과 정규식을 이용한 email과 password 유효성 검사를 진행
- 유효섬 검사를 통과하지 못 할 경우 에러 메시지를 반환 예외 처리 구현

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)

- 사용자가 발생시킬 수 있는 다양한 예외 케이스에 대해 고민하게 되었습니다. (예시)
- 문자열 데이터 입력 시 마지막에 빈 문자열이 포함되어 있는 경우 데이터 처리가 올바르게 되지 않아 유효성 검사에 빈 문자열 제거하는 로직을 추가하였습니다. (예시)

<br />

## :: 기타 질문 및 특이 사항

- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시)

2022-02-22 08:09 UTC, lordmyshepherd requested changes

2022-02-22 08:09 UTC, lordmyshepherd commented on houses/views.py
> +class BeingTheHostView(View):
class명으 `Host` 만으로 충분합니다.
```suggestion
class HostView(View):
```

2022-02-22 08:09 UTC, lordmyshepherd commented on houses/views.py
> +            ghost                    = Ghost.objects.get(name=ghost)
ghost와 house_type은 호스트 등록할때 선택하고 있죠?
그렇다면, name이 아니라 ghost_id, house_type_id로 받아서 insert 해주세요~
```suggestion
```

2022-02-22 08:09 UTC, lordmyshepherd commented on houses/views.py
> +            description = data["description"]
여러곳에서 재사용하지 않는 경우라변 굳이 다시한번 변수에 할당할 필요 없이, line 45~56에서 사용하는게 좋겠습니다.
읽어야될 코드의 수가 적은게 유지 보수하기에 좋습니다.

```
            house = House.objects.create(
                name        = data["name"],
```

2022-02-22 08:09 UTC, lordmyshepherd commented on houses/views.py
> +            ghost                    = Ghost.objects.get(name=ghost)
이부분도 house_type_id와 ghost_id로 값을 받게되면 굳이 db에서 다시한번 값을 받아올 필요가 없을 것 같습니다.

2022-02-22 08:09 UTC, lordmyshepherd commented on houses/views.py
> +                )
city랑 country는 이미 정규화되어서 db에 들어가 있어야되는 값이 아닌가요?
없는 경우 생성해주는 로직이 필요한가요?

2022-02-22 08:09 UTC, lordmyshepherd commented on houses/views.py
> +                    house     = House.objects.get(id=1)
이미 line 45에서 House 정보를 db에 insert하고 house객체를 반환받아서 변수에 할당했습니다.
그대로 사용하면 되겠습니다.
```suggestion
                    house     = house.id
```

2022-02-22 08:09 UTC, lordmyshepherd commented on core/s3_storages.py
> +s3_client = S3Client(AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, AWS_STORAGE_BUCKET_NAME)
잘 구현하셨습니다-!
class화 할 때, 고려하면 좋은 점들은 내일 라이브 리뷰때 설명드릴게요~

2022-02-23 06:18 UTC, lordmyshepherd commented
> class 설계시 SOLID 원치 고려
```python
# SRP, OSP, DI

class ImageUploader:
    def __init__(self, client, config):
        self.client = client

    def upload(self, image, directory):
        file_name = uuid.uuid4().hex[:10]

        self.client.upload_file(
                image,
                config.bucket_name,
                f'{directory}/{file_name}',
                ExtraArgs = {'ContentType' : file.content_type|
            )

        return f'https://{AWS_S3_CUSTOM_DOMAIN}/{folder_name}/{file_name}'

    def delete(self, image):
        return self.client.delete_object(..) 

class ImageHandler:
    def __init__(self, image, directory, client):
        self.image     = image
        self.directory = directory
        self.client    = client

    def save(self):
        self.client.upload(self.image, directory)


# 나중에 Naver Cloud로 변경을 원할 시 다음 처럼 ImageHandler 클래스를
# 수정하지 않고 자연스럽게 할 수 있다.
# (ImageUploader 클래스는 NaverCloud에 맞게 수정되어야 함)

#naver_image_uploader = ImageUploader(naver_cloud.client('cdn'), config) 
#image_handler  = ImageHandler(image, naver_image_uploader)
#image_handler.save()
```

```python
boto3_client = boto3.client(
    's3',
    aws_access_key_id     = AWS_ACCESS_KEY_ID,
    aws_secret_access_key = AWS_SECRET_ACCESS_KEY
)

image_uploader = ImageUploader(boto3_client, config)

class HouseView(View):
    def post(self, request, *args, **kwargs):
            for image in house_images:
                folder_name   = 'house'
                image_handler = ImageHandler(image, folder_name, image_uploader)
                image_url     = image_handler.save()
```

2022-02-24 02:55 UTC, jxngbxxm commented on houses/views.py
> +class BeingTheHostView(View):
반영해서 수정했습니다~!

2022-02-24 02:56 UTC, jxngbxxm commented on houses/views.py
> +            ghost                    = Ghost.objects.get(name=ghost)
정규화된 데이터라 피드백주신대로 DB를 호출하지 않게 Enum을 사용하여 리팩토링 하였습니다.

2022-02-24 02:57 UTC, jxngbxxm commented on houses/views.py
> +            description = data["description"]
반영했습니다~!

2022-02-24 02:57 UTC, jxngbxxm commented on houses/views.py
> +                    house     = House.objects.get(id=1)
테스트 과정에서 잠시 고쳤던 것을 체크하지 못하고 푸쉬했습니다.
다시 수정했습니다!

2022-02-24 04:15 UTC, lordmyshepherd approved these changes
LGTM 👍🏻

2022-02-24 04:15 UTC, lordmyshepherd commented on houses/views.py
> +            city, is_created_flag    = City.objects.get_or_create(
```suggestion
            country, is_countiy_created = Country.objects.get_or_create(name=country)
            city, is_city_created    = City.objects.get_or_create(
```

2022-02-24 04:15 UTC, lordmyshepherd commented on houses/views.py
> +
```python

class HouseTypeView(View):
    def get(self, request):
        return JsonResponse({"house_types" : [ {"id" : type.id, "name" : type.name for type in HousType])
```

2022-02-24 04:15 UTC, merged