29기 최형택 [ADD] Feature/house reservation post
wecode-bootcamp-korea/29-2nd-Airhnb-backend pull request #8
Opened 2022-02-23 11:02 UTC by knuckles6974

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)

- [X] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)

- 숙소정보와 예약정보를 활용한 예약등록관리 기능 구현 

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)

1. 에약시간 입력 데이터 유효성 검사 (예시 - 프론트)

- 입력창에 변화가 일어날 때 마다 유효성 검사 함수가 실행된다.
- 테스트 방법 : 예약시간 숙소정보 및 예약인원 input 데이터 입력

2. 예약시간 데이터 처리 (예시 - 백엔드)

- 데이터베이스를 바탕으로 한  유효성 검사를 진행
- 유효섬 검사를 통과하지 못 할 경우 에러 메시지를 반환 예외 처리 구현

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)

-변수에 대해서 조금이나마 알게되었습니다.

<br />

## :: 기타 질문 및 특이 사항

-

2022-02-23 13:36 UTC, lordmyshepherd requested changes

2022-02-23 13:36 UTC, lordmyshepherd commented on reservations/views.py
> +        #    reservation_id    = Reservation.objects.get(id=house_id).reservation_id
불필요한 주석은 지워주세요~
```suggestion
```

2022-02-23 13:36 UTC, lordmyshepherd commented on reservations/views.py
> +        #    headcount         = reservation.headcount
여기도 마찬가지로 불필요한 주석은 지워주세요!
```suggestion
```

2022-02-23 13:36 UTC, lordmyshepherd commented on reservations/views.py
> +           user_id   = data["user_id"]
user_id는 request message의 body로 받는 것이 아니라, client로부터 전달받은 access_token을 통해서 꺼내오셔야 합니다.
다시 말하면, 예약은 로그인한 회원만 할 수 있기 때문에, post method에 `@login_required`를 붙여서 만들어주셔야 합니다~

```python
@login_reqired
def post

```

2022-02-23 18:43 UTC, knuckles6974 commented on reservations/views.py
> +        #    reservation_id    = Reservation.objects.get(id=house_id).reservation_id
확인했습니다 .

2022-02-24 01:33 UTC, lordmyshepherd approved these changes

2022-02-24 01:33 UTC, lordmyshepherd commented on reservations/views.py
> +            return JsonResponse({"message":"KEY_ERROR"}, status = 401)
형택님 정말 깔끔합니다!! 👍🏻👍🏻
고생 많으셨습니다ㅜㅜ

2022-02-24 04:16 UTC, lordmyshepherd commented
컨플릭트 해결해서 올려주세요~

2022-02-24 04:30 UTC, jxngbxxm commented on reservations/views.py
> +            return JsonResponse({"message":"KEY_ERROR"}, status = 401)
👏 👏 👏 👏 👏 !!!

2022-02-24 05:04 UTC, lordmyshepherd approved these changes
LGTM 👍🏻

2022-02-24 05:04 UTC, merged